spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dmall?characterEncoding=UTF-8
      username: root
      password: 12345678

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: org.example.mall.entity
